env:
  global:
    - NVM_SYMLINK_CURRENT=true
    - PACKAGE="Nodejs" # Package name
    - SUBLIME_TEXT_VERSION="3"
    - PLUGIN_VERSION="2.0.5"
    # use UNITTESTING_TAG to specific tag of UnitTesting
    # - UNITTESTING_TAG="master"

branches:
  only:
    - master

# mutliple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
  include:
    - os: linux
      language: node_js
      node_js: "12"
      env:
        - NODEJS_VERSION="v12"
    - os: linux
      language: node_js
      node_js: "13"
      env:
        - NODEJS_VERSION="v13"
    - os: osx
      language: node_js
      node_js: "12"
      env:
        - NODEJS_VERSION="v12"
    - os: osx
      language: node_js
      node_js: "13"
      env:
        - NODEJS_VERSION="v13"

services:
  - xvfb

before_install:
  - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
  - export NVM_SYMLINK_CURRENT=true

install:
  - nvm alias default $NODEJS_VERSION; nvm use $NODEJS_VERSION
  # bootstrap the testing environment
  - sh travis.sh bootstrap
  # install Package Control and package dependencies
  - sh travis.sh install_package_control
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
          touch "$HOME/Library/Application Support/Sublime Text 3/Packages/Nodejs/.debug_plugin";
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          touch $HOME/.config/sublime-text-3/Packages/Nodejs/.debug_plugin;
    fi

script:
  # run tests with test coverage report
  - sh travis.sh run_tests
  # testing syntax_test files
  # - sh travis.sh run_syntax_tests

after_success:
  # remove the following if `coveralls` is not needed
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
          brew update;
          brew install python3;
          pip3 install python-coveralls;
          pip3 install coverage==4.5.4 codecov==2.0.15;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          pyenv install 3.8.1
          pip3 install python-coveralls;
          pip3 install coverage==4.5.4 codecov==2.0.15
    fi
  - coveralls
  - codecov

notifications:
  email: false

