env:
  global:
    - PACKAGE="Nodejs" # Package name
    - SUBLIME_TEXT_VERSION="3"
    # use UNITTESTING_TAG to specific tag of UnitTesting
    # - UNITTESTING_TAG="master"

branches:
  only:
    - master
    - refactor

# mutliple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
  include:
    - os: linux
      language: node_js
      node_js: "6"
    - os: linux
      language: node_js
      node_js: "8"
    - os: osx
      language: node_js
      node_js: "6"
    - os: osx
      language: node_js
      node_js: "8"


before_install:
  - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh
  # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
  - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
          export DISPLAY=:99.0;
          sh -e /etc/init.d/xvfb start;
    fi

install:
  # bootstrap the testing environment
  - sh travis.sh bootstrap
  # install Package Control and package denepdencies
  - sh travis.sh install_package_control
  - sh >$HOME/.config/sublime-text-3/Packages/Nodejs/.debug_plugin

script:
  # run tests with test coverage report
  - sh travis.sh run_tests --coverage
  # testing syntax_test files
  # - sh travis.sh run_syntax_tests

after_success:
  # remove the following if `coveralls` is not needed
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
          brew update;
          brew install python3;
          pip3 install python-coveralls;
          pip3 install codecov;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          apt-get update -qq
          apt-get install -qq python3
          pip install python-coveralls;
          pip install codecov;
    fi
  - coveralls
  - codecov

notifications:
  email: false
        